[package]
name = "google_maps"
version = "3.1.2"
authors = [ "Dylan Bowker <dylan.bowker@arkiteq.ca>" ]
edition = "2021"
categories = [ "api-bindings" ]
description = "An unofficial Google Maps Platform client library for the Rust programming language."
documentation = "https://docs.rs/google_maps"
keywords = [ "directions", "distance", "elevation", "geocoding", "timezone" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/google_maps"

[lib]
doctest = false

[features]
default = [
	"autocomplete", # Places API autocomplete-related services, other services are under "places" feature.
	"directions",
	"distance_matrix",
	"elevation",
	"geocoding",
	"places",
	"roads",
	"time_zone",
	"enable-reqwest",
	"reqwest/default-tls",
	"reqwest/gzip",
]
# Google Maps Client API features:
autocomplete = []
directions = [ "chrono", "chrono-tz" ]
distance_matrix = [ "chrono", "chrono-tz" ]
elevation = []
geo = [ "geo-types" ]
geocoding = []
places = [ "chrono", "chrono-tz" ]
roads = []
time_zone = [ "chrono", "chrono-tz" ]
# Reqwest features:
enable-reqwest = [ "reqwest", "backoff", "futures", "stream_throttle" ]
brotli = [ "reqwest/brotli" ]
gzip = [ "reqwest/gzip" ]
native-tls = [ "reqwest/default-tls" ]
rustls = [ "reqwest/rustls-tls" ]

[dependencies]
backoff = { version = "0.4", optional = true, features = [ "futures", "tokio" ] }
chrono = { version = "0.4", optional = true, features = [ "serde" ] }
chrono-tz = { version = "0.8", optional = true, features = [ "serde" ] }
futures = { version = "0.3", optional = true }
geo-types = { version = "0.7", optional = true, features = [ "serde" ] }
percent-encoding = "2.2"
phf = { version = "0.11", features = [ "macros" ] }
reqwest = { version = "0.11", optional = true, default-features = false }
rust_decimal = {version = "1", features = [ "serde-float" ] }
rust_decimal_macros = "1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
stream_throttle = { version = "0.4", optional = true }
tokio = { version = "1", optional = true, features = [ "time" ] }
tracing = { version = "0.1", features = [ "log" ] }

[badges]
maintenance = { status = "passively-maintained" }