[package]
name = "google_maps"
version = "1.0.3"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2018"
categories = [ "api-bindings" ]
description = "🗺 An unofficial Google Maps Platform client library for the Rust programming language."
documentation = "https://docs.rs/google_maps"
keywords = [ "distance", "elevation", "geocoding", "google", "maps" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/google_maps"

[dependencies]
chrono = { version = "^0.4.0", features = ["serde"] }
chrono-tz = { version = "^0.5.0", features = ["serde"] }
log = "^0.4.0"
percent-encoding = "^2.1.0"
rand = "^0.8.0"
reqwest = { version = "^0.11.0", features = ["blocking"] }
rust_decimal = {version = "^1.9.0", features = ["serde-float"] }
rust_decimal_macros = "^1.9.0"
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = "^1.0.0"

[badges]
travis-ci = { repository = "leontoeides/google_maps", branch = "master" }
maintenance = { status = "actively-developed" }