[package]
name = "google_maps"
version = "1.0.4"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2018"
categories = [ "api-bindings" ]
description = "🗺 An unofficial Google Maps Platform client library for the Rust programming language."
documentation = "https://docs.rs/google_maps"
keywords = [ "distance", "elevation", "geocoding", "google", "maps" ]
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/leontoeides/google_maps"

[lib]
doctest = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
log = "0.4"
percent-encoding = "^2.1"
rand = "0.8"
futures = "0.3"
reqwest = { version = "0.11", features = ["gzip"] }
rust_decimal = {version = "1.14", features = ["serde-float"] }
rust_decimal_macros = "1.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
stream_throttle = "0.4"
tokio = { version = "1", features = ["time"] }

[badges]
maintenance = { status = "passively-maintained" }
