[package]
name = "google_maps"
version = "0.1.0"
authors = ["Dylan Bowker <dylan.bowker@arkiteq.ca>"]
edition = "2018"
description = "Unofficial Google Maps Platform API for the Rust programming language."
license = "MIT OR Apache-2.0"

[dependencies]
percent-encoding = "2.1.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
time = "0.2.1"